autoencoder:
  enabled: true
  use_pretrained: true

transit:
  enabled: true
  use_pretrained: true

clustering:
  use_radial_average: true
  compare_radial_average: true

inference:
  use_radial_average: true
