"""Autoencoder training pipeline."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset

from planar.config import PlanarConfig
from planar.data_loader import load_dataset
from planar.metrics import HAS_MS_SSIM, reconstruction_components
from planar.models.autoencoder import ConvAutoencoder
from planar.preprocessing import preprocess_dataset
from planar.runtime import ensure_dir, get_device, save_json, set_seed
from planar.visualization import plot_metric_curves, plot_reconstructions

LOGGER = logging.getLogger(__name__)


@dataclass
class AutoencoderArtifacts:
    """Paths generated by the autoencoder pipeline."""

    out_dir: Path
    checkpoint_path: Path
    summary_path: Path


class DiskImageDataset(Dataset[torch.Tensor]):
    """Torch dataset wrapper for processed disk images."""

    def __init__(self, images: np.ndarray, augment_rot90: bool = False) -> None:
        """Initialize dataset.

        Args:
            images: Image array of shape `(N, H, W)`.
            augment_rot90: Whether to apply random 90-degree rotation.
        """
        self.images = images.astype(np.float32)
        self.augment_rot90 = augment_rot90

    def __len__(self) -> int:
        """Return dataset size."""
        return len(self.images)

    def __getitem__(self, idx: int) -> torch.Tensor:
        """Return one image tensor.

        Args:
            idx: Index in dataset.

        Returns:
            Tensor with shape `(1, H, W)`.
        """
        img = self.images[idx]
        if self.augment_rot90:
            k = np.random.randint(0, 4)
            img = np.rot90(img, k)

        return torch.from_numpy(img.copy()).unsqueeze(0)


def run_autoencoder_pipeline(config: PlanarConfig) -> AutoencoderArtifacts:
    """Train the autoencoder and persist checkpoint + diagnostics.

    Args:
        config: Global PLANAR configuration.

    Returns:
        Generated artifact paths.
    """
    set_seed(config.project.seed)

    out_dir = ensure_dir(Path(config.paths.artifacts_dir) / config.autoencoder.out_subdir)
    device = get_device(config.project.device)

    images, filenames, skipped = load_dataset(
        folder=config.paths.data_dir,
        max_files=config.paths.max_files,
        expected_shape=tuple(config.paths.expected_shape) if config.paths.expected_shape else None,
    )
    if len(images) == 0:
        raise RuntimeError("No FITS images were loaded. Check paths.data_dir and file integrity.")

    processed = preprocess_dataset(
        images,
        crop_size=config.autoencoder.crop_size,
        use_radial_average=config.autoencoder.use_radial_average,
    )

    train_idx, val_idx = train_test_split(
        np.arange(len(processed)),
        test_size=config.autoencoder.val_split,
        random_state=config.project.seed,
        shuffle=True,
    )

    train_images = processed[train_idx]
    val_images = processed[val_idx]

    train_ds = DiskImageDataset(train_images, augment_rot90=config.autoencoder.augment_rot90)
    val_ds = DiskImageDataset(val_images, augment_rot90=False)

    train_loader = DataLoader(
        train_ds,
        batch_size=config.autoencoder.batch_size,
        shuffle=True,
        num_workers=config.autoencoder.num_workers,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=config.autoencoder.batch_size,
        shuffle=False,
        num_workers=config.autoencoder.num_workers,
    )

    model = ConvAutoencoder(
        latent_dim=config.autoencoder.latent_dim,
        image_size=config.autoencoder.crop_size,
    ).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=config.autoencoder.lr)

    best_val = float("inf")
    wait = 0

    history: dict[str, list[float]] = {
        "train_loss": [],
        "val_loss": [],
        "train_mse": [],
        "val_mse": [],
        "train_ssim_loss": [],
        "val_ssim_loss": [],
    }

    checkpoint_path = out_dir / "autoencoder.pth"

    for epoch in range(1, config.autoencoder.epochs + 1):
        model.train()
        train_loss = 0.0
        train_mse = 0.0
        train_ssim = 0.0

        for batch in train_loader:
            batch = batch.to(device)

            optimizer.zero_grad()
            recon = model(batch)
            loss, mse, ssim_loss = reconstruction_components(recon, batch)
            loss.backward()
            optimizer.step()

            train_loss += float(loss.item())
            train_mse += float(mse.item())
            train_ssim += float(ssim_loss.item())

        train_loss /= max(len(train_loader), 1)
        train_mse /= max(len(train_loader), 1)
        train_ssim /= max(len(train_loader), 1)

        model.eval()
        val_loss = 0.0
        val_mse = 0.0
        val_ssim = 0.0

        with torch.no_grad():
            for batch in val_loader:
                batch = batch.to(device)
                recon = model(batch)
                loss, mse, ssim_loss = reconstruction_components(recon, batch)

                val_loss += float(loss.item())
                val_mse += float(mse.item())
                val_ssim += float(ssim_loss.item())

        val_loss /= max(len(val_loader), 1)
        val_mse /= max(len(val_loader), 1)
        val_ssim /= max(len(val_loader), 1)

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_mse"].append(train_mse)
        history["val_mse"].append(val_mse)
        history["train_ssim_loss"].append(train_ssim)
        history["val_ssim_loss"].append(val_ssim)

        LOGGER.info(
            "AE epoch=%03d train_loss=%.5f val_loss=%.5f train_mse=%.5f val_mse=%.5f",
            epoch,
            train_loss,
            val_loss,
            train_mse,
            val_mse,
        )

        if val_loss < best_val:
            best_val = val_loss
            wait = 0
            torch.save(
                {
                    "state_dict": model.state_dict(),
                    "latent_dim": config.autoencoder.latent_dim,
                    "crop_size": config.autoencoder.crop_size,
                    "seed": config.project.seed,
                },
                checkpoint_path,
            )
        else:
            wait += 1
            if wait >= config.autoencoder.patience:
                LOGGER.info("AE early stopping at epoch %d", epoch)
                break

    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint["state_dict"])
    model.eval()

    with torch.no_grad():
        sample = torch.from_numpy(val_images[:16]).to(device).unsqueeze(1)
        recon = model(sample).squeeze(1).cpu().numpy()

    plot_metric_curves(
        history["train_loss"],
        history["val_loss"],
        title="Autoencoder Reconstruction Loss",
        ylabel="Loss",
        save_path=out_dir / "loss_curve.png",
    )
    plot_metric_curves(
        history["train_mse"],
        history["val_mse"],
        title="Autoencoder MSE",
        ylabel="MSE",
        save_path=out_dir / "mse_curve.png",
    )

    if HAS_MS_SSIM:
        plot_metric_curves(
            history["train_ssim_loss"],
            history["val_ssim_loss"],
            title="Autoencoder MS-SSIM Loss Component",
            ylabel="1 - MS-SSIM",
            save_path=out_dir / "ms_ssim_curve.png",
        )

    plot_reconstructions(
        inputs=val_images[:16],
        reconstructions=recon,
        save_path=out_dir / "recon_examples.png",
        n_examples=8,
    )

    summary = {
        "num_files_loaded": len(filenames),
        "num_files_skipped": len(skipped),
        "skipped_examples": skipped[:10],
        "train_size": int(len(train_images)),
        "val_size": int(len(val_images)),
        "best_val_loss": float(best_val),
        "ms_ssim_available": HAS_MS_SSIM,
    }
    summary_path = out_dir / "train_summary.json"
    save_json(summary, summary_path)

    LOGGER.info("Autoencoder artifacts written to %s", out_dir)

    return AutoencoderArtifacts(out_dir=out_dir, checkpoint_path=checkpoint_path, summary_path=summary_path)
