"""Latent-space clustering pipeline."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch

from planar.config import PlanarConfig
from planar.data_loader import load_dataset
from planar.metrics import clustering_quality_scores, clustering_stability_scores
from planar.models.autoencoder import ConvAutoencoder
from planar.models.clustering import cluster_latent_space, reduce_dim
from planar.preprocessing import preprocess_dataset
from planar.runtime import ensure_dir, get_device, save_json, set_seed
from planar.science_validation import (
    axis_ratio_proxies,
    brightness_proxy,
    cluster_bias_summary,
    cluster_interpretation_rows,
)
from planar.visualization import (
    plot_bias_scatter,
    plot_cluster_means,
    plot_embedding_scatter,
    plot_proxy_by_cluster,
    plot_radial_intensity_profiles,
)

LOGGER = logging.getLogger(__name__)


@dataclass
class ClusteringArtifacts:
    """Paths generated by the clustering pipeline."""

    out_dir: Path
    summary_path: Path


def _debias_latent_vectors(
    latent_vectors: np.ndarray,
    brightness: np.ndarray,
    axis_ratio: np.ndarray,
) -> tuple[np.ndarray, dict[str, float]]:
    """Linearly remove nuisance proxy components from latent vectors.

    Args:
        latent_vectors: Latent vectors `(N, D)`.
        brightness: Brightness proxy `(N,)`.
        axis_ratio: Orientation proxy `(N,)`.

    Returns:
        Debiased latent vectors and variance-retention diagnostics.
    """
    b = (brightness - brightness.mean()) / (brightness.std() + 1e-8)
    a = (axis_ratio - axis_ratio.mean()) / (axis_ratio.std() + 1e-8)
    design = np.stack([np.ones_like(b), b, a], axis=1).astype(np.float32)
    beta, _, _, _ = np.linalg.lstsq(design, latent_vectors, rcond=None)
    nuisance_component = design @ beta
    debiased = latent_vectors - nuisance_component

    total_var = float(np.var(latent_vectors))
    remain_var = float(np.var(debiased))
    retention = remain_var / max(total_var, 1e-8)

    return debiased.astype(np.float32), {
        "latent_variance_before": total_var,
        "latent_variance_after": remain_var,
        "variance_retention": retention,
    }


def _batched_encode(model: ConvAutoencoder, data: np.ndarray, batch_size: int, device: str) -> np.ndarray:
    """Encode images to latent vectors using mini-batches.

    Args:
        model: Trained autoencoder.
        data: Input image array `(N, H, W)`.
        batch_size: Batch size.
        device: Runtime device.

    Returns:
        Latent matrix `(N, D)`.
    """
    all_latents: list[np.ndarray] = []
    model.eval()

    with torch.no_grad():
        for i in range(0, len(data), batch_size):
            batch = torch.from_numpy(data[i : i + batch_size]).to(device).unsqueeze(1)
            latent = model.encode(batch).cpu().numpy()
            all_latents.append(latent)

    return np.concatenate(all_latents, axis=0)


def _write_interpretation_csv(rows: list[dict[str, object]], path: Path) -> None:
    """Persist cluster interpretation rows to CSV.

    Args:
        rows: Interpretation rows.
        path: Output CSV path.
    """
    with path.open("w", encoding="utf-8") as handle:
        handle.write(
            "cluster_id,count,mean_brightness,std_brightness,mean_axis_ratio,std_axis_ratio,"
            "estimated_ring_count,estimated_gap_count,derivative_peak_count,"
            "mean_gap_width_px,max_gap_width_px,morphology_label,gap_widths_px\n"
        )
        for row in rows:
            mean_gap = "" if row["mean_gap_width_px"] is None else f"{row['mean_gap_width_px']:.3f}"
            max_gap = "" if row["max_gap_width_px"] is None else f"{row['max_gap_width_px']:.3f}"
            gap_widths = ";".join(str(value) for value in row["gap_widths_px"])
            handle.write(
                f"{row['cluster_id']},{row['count']},{row['mean_brightness']:.8f},"
                f"{row['std_brightness']:.8f},{row['mean_axis_ratio']:.8f},"
                f"{row['std_axis_ratio']:.8f},{row['estimated_ring_count']},{row['estimated_gap_count']},"
                f"{row['derivative_peak_count']},{mean_gap},{max_gap},{row['morphology_label']},{gap_widths}\n"
            )


def run_clustering_pipeline(
    config: PlanarConfig,
    model_path: str | Path | None = None,
) -> ClusteringArtifacts:
    """Run latent extraction, clustering, and scientific diagnostics.

    Args:
        config: Global PLANAR configuration.
        model_path: Optional autoencoder checkpoint path.

    Returns:
        Generated artifact paths.
    """
    set_seed(config.project.seed)

    out_dir = ensure_dir(Path(config.paths.artifacts_dir) / config.clustering.out_subdir)
    device = get_device(config.project.device)

    checkpoint_path = Path(model_path) if model_path else Path(config.paths.artifacts_dir) / config.autoencoder.out_subdir / "autoencoder.pth"
    checkpoint = torch.load(checkpoint_path, map_location="cpu")

    crop_size = int(checkpoint.get("crop_size", config.autoencoder.crop_size))
    latent_dim = int(checkpoint.get("latent_dim", config.autoencoder.latent_dim))

    model = ConvAutoencoder(latent_dim=latent_dim, image_size=crop_size)
    model.load_state_dict(checkpoint["state_dict"])
    model.to(device)

    images, filenames, skipped = load_dataset(
        folder=config.paths.data_dir,
        max_files=config.paths.max_files,
        expected_shape=tuple(config.paths.expected_shape) if config.paths.expected_shape else None,
    )
    if len(images) == 0:
        raise RuntimeError("No FITS images were loaded for clustering.")

    processed = preprocess_dataset(
        images,
        crop_size=crop_size,
        use_radial_average=config.clustering.use_radial_average,
    )
    brightness = brightness_proxy(images, crop_size=crop_size)
    axis_ratio = axis_ratio_proxies(processed)

    latent = _batched_encode(model, processed, batch_size=config.clustering.batch_size, device=device)
    debias_diagnostics: dict[str, float] | None = None
    latent_for_clustering = latent
    if config.clustering.debias_nuisance_latent:
        latent_for_clustering, debias_diagnostics = _debias_latent_vectors(
            latent_vectors=latent,
            brightness=brightness,
            axis_ratio=axis_ratio,
        )

    labels, _, method_used = cluster_latent_space(
        latent_for_clustering,
        method=config.clustering.method,
        min_cluster_size=config.clustering.min_cluster_size,
        n_clusters=config.clustering.n_clusters,
        random_state=config.project.seed,
    )
    embedding, _, reducer_name = reduce_dim(
        latent_for_clustering,
        method=config.clustering.embedder,
        random_state=config.project.seed,
    )

    metrics = clustering_quality_scores(latent_for_clustering, labels)
    stability = clustering_stability_scores(
        latent_vectors=latent_for_clustering,
        method=config.clustering.method,
        min_cluster_size=config.clustering.min_cluster_size,
        n_clusters=config.clustering.n_clusters,
        num_runs=config.clustering.stability_runs,
        noise_std=config.clustering.stability_noise_std,
        random_state=config.project.seed,
    )

    rng = np.random.default_rng(config.project.seed)
    shuffled_labels = labels.copy()
    rng.shuffle(shuffled_labels)
    shuffled_label_metrics = clustering_quality_scores(latent_for_clustering, shuffled_labels)

    latent_permuted = latent_for_clustering.copy()
    for j in range(latent_permuted.shape[1]):
        latent_permuted[:, j] = latent_permuted[rng.permutation(len(latent_permuted)), j]
    perm_labels, _, perm_method = cluster_latent_space(
        latent_permuted,
        method=config.clustering.method,
        min_cluster_size=config.clustering.min_cluster_size,
        n_clusters=config.clustering.n_clusters,
        random_state=config.project.seed + 997,
    )
    perm_metrics = clustering_quality_scores(latent_permuted, perm_labels)
    negative_controls = {
        "shuffled_labels": shuffled_label_metrics,
        "permuted_latent_refit": {
            "method_used": perm_method,
            "metrics": perm_metrics,
        },
    }

    np.save(out_dir / "latent_vectors.npy", latent)
    np.save(out_dir / "embedding_2d.npy", embedding)
    np.save(out_dir / "labels.npy", labels)

    with (out_dir / "cluster_labels.csv").open("w", encoding="utf-8") as handle:
        handle.write("filename,label\n")
        for filename, label in zip(filenames, labels):
            handle.write(f"{filename},{int(label)}\n")

    plot_embedding_scatter(
        embedding,
        labels,
        save_path=out_dir / "latent_scatter.png",
        title=f"Latent Embedding ({reducer_name.upper()})",
    )
    plot_cluster_means(processed, labels, save_path=out_dir / "cluster_means.png")
    plot_radial_intensity_profiles(processed, labels, save_path=out_dir / "radial_profiles.png")

    bias = cluster_bias_summary(labels, brightness=brightness, axis_ratio=axis_ratio)
    interpretation = cluster_interpretation_rows(
        processed_images=processed,
        labels=labels,
        brightness=brightness,
        axis_ratio=axis_ratio,
    )

    _write_interpretation_csv(interpretation, out_dir / "cluster_interpretation.csv")
    save_json(bias, out_dir / "cluster_bias_summary.json")
    save_json({"clusters": interpretation}, out_dir / "cluster_interpretation.json")
    save_json(stability, out_dir / "cluster_stability_summary.json")
    save_json(negative_controls, out_dir / "negative_controls.json")

    plot_proxy_by_cluster(
        brightness,
        labels,
        ylabel="Mean Intensity",
        title="Brightness Proxy by Cluster",
        save_path=out_dir / "brightness_by_cluster.png",
    )
    plot_proxy_by_cluster(
        axis_ratio,
        labels,
        ylabel="Axis Ratio",
        title="Orientation Proxy by Cluster",
        save_path=out_dir / "axis_ratio_by_cluster.png",
    )
    plot_bias_scatter(
        brightness=brightness,
        axis_ratio=axis_ratio,
        labels=labels,
        save_path=out_dir / "brightness_vs_orientation.png",
    )

    summary = {
        "num_images": len(filenames),
        "num_skipped": len(skipped),
        "method_requested": config.clustering.method,
        "method_used": method_used,
        "reducer": reducer_name,
        "debias_nuisance_latent": bool(config.clustering.debias_nuisance_latent),
        "debias_diagnostics": debias_diagnostics,
        "metrics": metrics,
        "bias_summary": bias,
        "stability_summary": stability,
        "negative_controls": negative_controls,
    }
    summary_path = out_dir / "clustering_summary.json"
    save_json(summary, summary_path)

    LOGGER.info(
        "Clustering complete: method=%s reducer=%s silhouette=%s noise=%.3f",
        method_used,
        reducer_name,
        metrics.get("silhouette"),
        metrics.get("noise_fraction", 0.0),
    )

    return ClusteringArtifacts(out_dir=out_dir, summary_path=summary_path)
