"""Transit classifier training and evaluation pipeline."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset

from planar.config import PlanarConfig
from planar.models.transit_classifier import TransitCNN
from planar.runtime import ensure_dir, get_device, save_json, set_seed
from planar.transit_sim import generate_transit_dataset
from planar.visualization import plot_metric_curves, plot_roc

LOGGER = logging.getLogger(__name__)


@dataclass
class TransitArtifacts:
    """Paths generated by transit training pipeline."""

    out_dir: Path
    checkpoint_path: Path
    summary_path: Path


def _to_loader(X: np.ndarray, y: np.ndarray, batch_size: int, shuffle: bool) -> DataLoader:
    """Create torch dataloader from arrays.

    Args:
        X: Features `(N, T)`.
        y: Labels `(N,)`.
        batch_size: Batch size.
        shuffle: Whether to shuffle.

    Returns:
        Torch data loader.
    """
    x_tensor = torch.from_numpy(X).float().unsqueeze(1)
    y_tensor = torch.from_numpy(y).float().unsqueeze(1)
    dataset = TensorDataset(x_tensor, y_tensor)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)


def _normalize_lightcurves(X: np.ndarray) -> np.ndarray:
    """Normalize each light curve independently.

    Args:
        X: Input matrix `(N, T)`.

    Returns:
        Normalized matrix.
    """
    X = X.astype(np.float32)
    med = np.median(X, axis=1, keepdims=True).astype(np.float32)
    centered = (X / (med + 1e-8)) - 1.0
    mean = centered.mean(axis=1, keepdims=True)
    std = centered.std(axis=1, keepdims=True)
    return ((centered - mean) / (std + 1e-8)).astype(np.float32)


def _predict_scores(model: TransitCNN, loader: DataLoader, device: str) -> tuple[np.ndarray, np.ndarray]:
    """Predict probabilities and return true labels.

    Args:
        model: Trained model.
        loader: Data loader.
        device: Runtime device.

    Returns:
        True labels and predicted scores.
    """
    model.eval()
    y_true: list[np.ndarray] = []
    y_score: list[np.ndarray] = []

    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(device)
            logits = model(xb)
            probs = torch.sigmoid(logits)
            y_true.append(yb.numpy())
            y_score.append(probs.cpu().numpy())

    return np.concatenate(y_true).ravel(), np.concatenate(y_score).ravel()


def run_transit_pipeline(config: PlanarConfig) -> TransitArtifacts:
    """Train transit classifier and run stress evaluation.

    Args:
        config: Global PLANAR configuration.

    Returns:
        Generated artifact paths.
    """
    set_seed(config.project.seed)

    out_dir = ensure_dir(Path(config.paths.artifacts_dir) / config.transit.out_subdir)
    device = get_device(config.project.device)

    X, y, _ = generate_transit_dataset(
        n_samples=config.transit.samples,
        num_points=config.transit.num_points,
        seed=config.project.seed,
    )
    X = _normalize_lightcurves(X)

    idx = np.arange(len(X))
    train_idx, test_idx = train_test_split(
        idx,
        test_size=config.transit.test_split,
        random_state=config.project.seed,
        stratify=y,
    )

    relative_val = config.transit.val_split / (1.0 - config.transit.test_split)
    train_idx, val_idx = train_test_split(
        train_idx,
        test_size=relative_val,
        random_state=config.project.seed,
        stratify=y[train_idx],
    )

    train_loader = _to_loader(X[train_idx], y[train_idx], config.transit.batch_size, shuffle=True)
    val_loader = _to_loader(X[val_idx], y[val_idx], config.transit.batch_size, shuffle=False)
    test_loader = _to_loader(X[test_idx], y[test_idx], config.transit.batch_size, shuffle=False)

    model = TransitCNN().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=config.transit.lr)
    criterion = torch.nn.BCEWithLogitsLoss()

    best_auc = -1.0
    wait = 0

    history: dict[str, list[float]] = {
        "train_loss": [],
        "val_loss": [],
        "val_auc": [],
    }

    checkpoint_path = out_dir / "transit_classifier.pth"

    for epoch in range(1, config.transit.epochs + 1):
        model.train()
        train_loss = 0.0

        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)

            optimizer.zero_grad()
            logits = model(xb)
            loss = criterion(logits, yb)
            loss.backward()
            optimizer.step()
            train_loss += float(loss.item())

        train_loss /= max(len(train_loader), 1)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for xb, yb in val_loader:
                xb = xb.to(device)
                yb = yb.to(device)
                logits = model(xb)
                loss = criterion(logits, yb)
                val_loss += float(loss.item())

        val_loss /= max(len(val_loader), 1)
        y_val_true, y_val_score = _predict_scores(model, val_loader, device)
        val_auc = float(roc_auc_score(y_val_true, y_val_score))

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["val_auc"].append(val_auc)

        LOGGER.info(
            "Transit epoch=%03d train_loss=%.5f val_loss=%.5f val_auc=%.5f",
            epoch,
            train_loss,
            val_loss,
            val_auc,
        )

        if val_auc > best_auc:
            best_auc = val_auc
            wait = 0
            torch.save(
                {
                    "state_dict": model.state_dict(),
                    "num_points": config.transit.num_points,
                    "seed": config.project.seed,
                },
                checkpoint_path,
            )
        else:
            wait += 1
            if wait >= config.transit.patience:
                LOGGER.info("Transit early stopping at epoch %d", epoch)
                break

    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint["state_dict"])

    y_test_true, y_test_score = _predict_scores(model, test_loader, device)
    test_auc = float(roc_auc_score(y_test_true, y_test_score))
    roc_auc = plot_roc(y_test_true, y_test_score, out_dir / "roc_curve.png")

    X_stress, y_stress, _ = generate_transit_dataset(
        n_samples=config.transit.stress_eval_size,
        num_points=config.transit.num_points,
        seed=config.transit.stress_seed,
        stress_mode=True,
    )
    X_stress = _normalize_lightcurves(X_stress)
    stress_loader = _to_loader(X_stress, y_stress, config.transit.batch_size, shuffle=False)
    y_stress_true, y_stress_score = _predict_scores(model, stress_loader, device)
    stress_auc = float(roc_auc_score(y_stress_true, y_stress_score))
    stress_roc_auc = plot_roc(y_stress_true, y_stress_score, out_dir / "stress_roc_curve.png")

    plot_metric_curves(
        history["train_loss"],
        history["val_loss"],
        title="Transit Classifier BCE Loss",
        ylabel="Loss",
        save_path=out_dir / "loss_curve.png",
    )

    plot_metric_curves(
        history["val_auc"],
        history["val_auc"],
        title="Transit Classifier Validation AUC",
        ylabel="AUC",
        save_path=out_dir / "auc_curve.png",
    )

    summary = {
        "samples": int(config.transit.samples),
        "num_points": int(config.transit.num_points),
        "train_size": int(len(train_idx)),
        "val_size": int(len(val_idx)),
        "test_size": int(len(test_idx)),
        "best_val_auc": float(best_auc),
        "test_auc": float(test_auc),
        "roc_auc": float(roc_auc),
        "stress_eval_size": int(config.transit.stress_eval_size),
        "stress_test_auc": float(stress_auc),
        "stress_roc_auc": float(stress_roc_auc),
    }
    summary_path = out_dir / "train_summary.json"
    save_json(summary, summary_path)

    LOGGER.info("Transit training complete. test_auc=%.4f stress_auc=%.4f", test_auc, stress_auc)

    return TransitArtifacts(out_dir=out_dir, checkpoint_path=checkpoint_path, summary_path=summary_path)
